WIP: Review project README + change for F4PGA
chipsalliance/fpga-tool-perf pull request #390
Opened 2022-01-25 07:54 UTC by mgielda

Reviewed the README and while I was at it, also switched to the new name, so this will have to wait until the rename is completed + will require changes in the code (as symbiflow is used in make env etc)

2022-01-27 14:14 UTC, acomodi requested changes
LGTM, apart from some changes to be added to the Makefile as well (see comment below)

2022-01-27 14:14 UTC, acomodi commented on README.md
> +make install_f4pga
This change should be reflected also in the Makefile to have them in sync

2022-01-27 17:48 UTC, mithro commented
Make sure the symbiflow command names are kept for backward compatibility...

2022-08-18 16:58 UTC, umarcor commented
Superseeded by #454.

2022-08-18 22:24 UTC, closed without merging